### ISSUE TITLE
1.5.1 crashing in Bluestacks emulator

### ISSUE THREAD

**Issue by jonapoul** [jonapoul/cotgenerator#10]
Received reports of crash-on-launch for v1.5.1. Apparently works fine on v1.5.

**Comment by jonapoul** [comment]
Tried reproducing on my machine, seems to work find

**Comment by jonapoul** [comment]
Turned out to be because of the following stack trace:

```
2020-07-14 20:22:39.411 3457-3457/? E/(CotThread.java:81): java.lang.IllegalAccessException: Class java.lang.Class<com.jon.common.service.CotThread> cannot access  method void com.jon.cotgenerator.GeneratorCotFactory.<init>(android.content.SharedPreferences) of class java.lang.Class<com.jon.cotgenerator.GeneratorCotFactory>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at com.jon.common.service.CotThread.buildCotFactory(CotThread.java:78)
        at com.jon.common.service.CotThread.<init>(CotThread.java:41)
        at com.jon.common.service.TcpCotThread.<init>(TcpCotThread.java:25)
        at com.jon.common.service.CotThread.fromPrefs(CotThread.java:32)
        at com.jon.common.service.CotManager.start(CotManager.java:22)
        at com.jon.common.service.CotService.start(CotService.java:105)
        at com.jon.common.ui.MainActivity.onOptionsItemSelected(MainActivity.java:111)
        at android.app.Activity.onMenuItemSelected(Activity.java:3265)
        at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
        at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
        at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
        at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
        at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
        at android.view.View.performClick(View.java:5794)
        at android.view.View$PerformClick.run(View.java:22729)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6138)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

So I hadn't recompiled the `common` module before building the APK, and it was trying to access a method that didn't exist any more. God I'm dumb
