### ISSUE TITLE
Allow protobuf output over TCP/SSL

### ISSUE THREAD

**Issue by jonapoul** [jonapoul/cotgenerator#19]
Currently only allowed for UDP. The protocol negotiation for TAK Server is listed in [this document from the ATAK repo](https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/master/commoncommo/core/impl/protobuf/protocol.txt), so we'll need to implement this as part of TcpCotThread to get the server to read the packets properly.

**Comment by jonapoul** [comment]
First attempt: negotiation works fine but when I then try to send an encoded packet, I get:
```
2020-07-16 22:48:31.285 31648-31732/com.jon.cotgenerator E/(TcpCotThread.java:80): javax.net.ssl.SSLException: Write error: ssl=0x7b611cf048: I/O error during system call, Broken pipe
        at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
        at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:626)
        at java.io.OutputStream.write(OutputStream.java:75)
        at com.jon.common.service.TcpCotThread.sendToDestination(TcpCotThread.java:95)
        at com.jon.common.service.TcpCotThread.run(TcpCotThread.java:72)
        at com.jon.common.service.SslCotThread.run(SslCotThread.java:37)
```

The exception server-side is:
```
2020-07-16-19:55:10.237 ERROR - Exception in onDataReceived! com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
```
implying that the packet is being clipped somewhere between transmission on my end and parsing on the server.
